runtime: nodejs20 # or another supported version

instance_class: F2

env_variables:
  MONGODB_URL: 'mongodb+srv://mlychndn:<password>@cluster0.txai0.mongodb.net/User?retryWrites=true&w=majority'
  PASSWORD: 'tithiSuriya'
  SECRET: 'This-secret-is-for-creating-jwt'
  EXPIRED: '5h'
  USER: '9f249446470d27'
  PASS: '362658957f8f32'
